---
# Define a Service to expose database to other service
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: monitoring
  labels:
    app: postgres-auth
    tier: database
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-auth
    tier: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-auth
  namespace: monitoring
  labels:
    app: postgres-auth
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: monitoring
  labels:
    app: postgres-auth
    tier: database
spec:
  selector:
    matchLabels:
      app: postgres-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-auth
        tier: database
    spec:
      containers:
        - name: postgres-auth
          image: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials-auth
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials-auth
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap-auth
                  key: name
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: postgres-data  # Specify a subdirectory
              name: postgres-persistance-storage-auth
      volumes:
        - name: postgres-persistance-storage-auth
          persistentVolumeClaim:
            claimName: postgres-pv-claim-auth
